(set *facts*
  [
    [plan p1]
    [plan-source p1 remote-work-gap-fill]
    [plan-goal p1 post-gap-consistency]
    [plan-claim p1 c1]
    [plan-conclusion p1 k3]

    [term c1 claim]
    [action c1 allow]
    [target c1 threeday]
    [population c1 all-employees]
    [benefit c1 deep-work]
    [benefit c1 employee-focus]
    [benefit c1 reduced-stress]
    [benefit c1 retention]
    [modality c1 deontic-recommendation]
    [scope-status c1 conditional]

    [term threeday known]
    [definition threeday "employees may work remotely three days per week"]
    [remote-days threeday three-days-per-week]

    [term accountfear known]
    [definition accountfear "executives worry about productivity loss"]
    [term slackrule known]
    [policy-condition c1 slackrule]
    [rule-type slackrule availability]
    [availability-window slackrule workday]
    [response-time slackrule ten-minutes]
    [undermines slackrule deep-work]
    [user-supplied G3 slackrule]

    [term hrguides known]
    [definition hrguides "company-wide remote-work guidelines"]
    [policy-rule hrguides uniform-rules]
    [prohibits hrguides exceptions]
    [user-supplied G4 hrguides]

    [term newoffice known]
    [definition newoffice "new employees work in the office four days per week for their first six months"]
    [group-rule newoffice new-employees]
    [required-location newoffice office]
    [required-office-days newoffice four-days-per-week]
    [duration newoffice six-months]
    [exception-rule newoffice]
    [exception-group newoffice new-employees]
    [exception-to newoffice c1]
    [conflicts-with-target newoffice threeday]
    [user-supplied G7 newoffice]

    [term equitygap known]
    [definition equitygap "employees who cannot benefit equally from remote work need alternatives"]
    [term alternatives known]
    [definition alternatives "employees who cannot benefit from remote work may work from the office instead"]
    [mitigates alternatives equitygap]
    [needs-equivalence-check alternatives]
    [equivalence-status alternatives unknown]
    [user-supplied G5 alternatives]

    [conclusion k3 necessaryresp]
    [value-type k3 necessity]
    [criteria-status k3 grounded]
    [necessity-ground k3 quitrisk]
    [ground-claim g14 quitrisk necessaryresp]
    [infers-to g14 k3]
    [term necessaryresp known]
    [definition necessaryresp "the policy is necessary to address retention risk"]
    [term quitrisk known]
    [definition quitrisk "employees will leave if the company does not offer more remote flexibility"]
    [counterfactual quitrisk]
    [evidence-status quitrisk unknown]
    [user-supplied G6 quitrisk]
  ])
