(set *facts*
  [
    [plan p1]
    [plan-source p1 edge-stage]
    [plan-goal p1 redundant-middle-syntactic]
    [term source known]
    [term target known]
    [claim c1 causal source target]
    [mechanism c1 bridge]
    [modality c1 possible]
    [scope c1 conditional]
    [stage-chain-min c1 3]
    [stage s1 collect-data]
    [stage-of s1 c1]
    [stage-order s1 1]
    [stage s2 gather-observations]
    [stage-of s2 c1]
    [stage-order s2 2]
    [stage s3 choose-action]
    [stage-of s3 c1]
    [stage-order s3 3]
    [stage-next c1 s1 s2]
    [stage-next c1 s2 s3]
    [stage-bridge s1 s2 data-processing]
    [stage-bridge s2 s3 action-selection]
  ])
